advertisements/urls.py
from django.conf.urls import url

from advertisements.views import AdvertisementDetail, AdvertisementCreate, \
    AdvertisementUpdate, AdvertisementDelete

urlpatterns = [url(r'^(?P<pk>\d+)/$', AdvertisementDetail.as_view(),
                   name="advertisement_detail"),
               url(r'^create/$', AdvertisementCreate.as_view(),
                    name="advertisement_create"),
               url(r'^update/(?P<pk>\d+)/$', AdvertisementUpdate.as_view(),
                    name="advertisement_update"),
               url(r'^delete/(?P<pk>\d+)/$', AdvertisementDelete.as_view(),
                   name="advertisement_delete"),
               ]

api/urls.py
from api.views import CityList, CategoryList, SubCategoryList, \
    ListCreateAdvertisement, DetailUpdateDeleteAdvertisement, CityDetail, \
    CategoryDetail, SubCategoryDetail, UserList, UserDetail
from django.conf.urls import url


urlpatterns = [
    url(r'^users/$', UserList.as_view(), name="list_users"),
    url(r'^users/(?P<pk>\d+)/$', UserDetail.as_view(), name="detail_user"),
    url(r'^cities/(?P<pk>\d+)/$', CityDetail.as_view(), name="detail_city"),
    url(r'^cities/$', CityList.as_view(), name="list_cities"),
    url(r'^categories/$', CategoryList.as_view(), name="list_categories"),
    url(r'^categories/(?P<pk>\d+)/$', CategoryDetail.as_view(), name="detail_category"),
    url(r'^subcategories/$', SubCategoryList.as_view(),
        name="list_subcategories"),
    url(r'^subcategories/(?P<pk>\d+)/$', SubCategoryDetail.as_view(),
        name="subdetail_category"),
    url(r'^advertisements/$', ListCreateAdvertisement.as_view(),
    name="list_create_advertisement"),
    url(r'^advertisements/(?P<pk>\d+)/$', DetailUpdateDeleteAdvertisement.as_view(), name="detail_update_delete_advertisement")
]

fredslist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.cache import cache_page

from advertisements.views import CategoryView, SubCategoryView, MainPageView,\
    AllCityList, CityRedirect, UserDetail
from profiles.views import RegisterUser

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/register/$', RegisterUser.as_view(), name="register"),
    url(r'^users/detail/(?P<pk>\d+)/$', UserDetail.as_view(),
        name="user_detail"),
    url(r'^advertisements/', include("advertisements.urls", namespace="ads")),
    url(r'^subcategory/(?P<pk>\d+)/$', SubCategoryView.as_view(),
        name="subcategory_list"),
    url(r'^category/(?P<pk>\d+)/$', CategoryView.as_view(),
        name="category_list"),
    url(r'^allcities/$', AllCityList.as_view(), name="all_cities"),
    url(r'cities/redirect/(?P<id>\d+)/$', CityRedirect.as_view(),
        name="city_redirect"),
    url(r"^api/", include('api.urls', namespace="api")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^logout/$', logout, {'next_page': reverse_lazy("main_page")},
        name='logout'),
    url(r'^$', MainPageView.as_view(), name="main_page"),
    url('^', include('django.contrib.auth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

advertisements/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class City(models.Model):

    title = models.CharField(max_length=255)
    state = models.CharField(max_length=2, null=True)

    def __str__(self):
        return self.title

    class Meta:
        unique_together = (("title", "state"),)


class Category(models.Model):
    """
    A broad category of advertisements. It's view displays all of the items
    within it's subcategories.
    """
    title = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title


class SubCategory(models.Model):
    """
    Very similar to Category.
    """
    title = models.CharField(max_length=255, null=True)
    category = models.ForeignKey(Category, null=True)

    def __str__(self):
        return self.title


class Advertisement(models.Model):
    """
    The main object of the site. Ads are filtered by user, category, or
    subcategory and are displayed in a number of ways.
    """
    title = models.CharField(max_length=255, null=True)
    description = models.TextField(max_length=2000, null=True)
    price = models.IntegerField(null=True, blank=True)
    phone_number = models.CharField(max_length=10, null=True, blank=True)
    image = models.ImageField(upload_to="advertisement_images/", null=True,
                              blank=True)
    email = models.EmailField(max_length=254, null=True)
    zipcode = models.CharField(max_length=10, null=True, blank=True)
    archived = models.BooleanField(default=False)

    city = models.ForeignKey(City, null=True)
    subcategory = models.ForeignKey(SubCategory, null=True)
    user = models.ForeignKey(User, null=True, blank=True)

    created_time = models.DateTimeField(auto_now_add=True, null=True)
    modified_time = models.DateTimeField(auto_now=True, null=True)

    @property
    def display_date(self):
        date = self.modified_time
        return "{:%b} {}".format(date, date.day)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-modified_time"]
        default_related_name = "advertisements"

advertisements/forms.py
from django import forms
from advertisements.models import Advertisement


class AdvertisementForm(forms.ModelForm):

    class Meta:
        model = Advertisement
        fields = ("title", "description", "price", "subcategory",
                   "phone_number", "image", "email", "zipcode")


class AdvertisementUpdateForm(forms.ModelForm):

    class Meta:
        model = Advertisement
        fields = ("description", "price", "phone_number", "image", "zipcode")

advertisements/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import ListView, DetailView, CreateView,\
    RedirectView, UpdateView, DeleteView
from rest_framework.authtoken.models import Token

from advertisements.forms import AdvertisementForm, AdvertisementUpdateForm
from advertisements.models import Advertisement, SubCategory, Category, City

import logging

logger = logging.getLogger("ads")

def get_current_city(request):
    """
    Checks for a city to filter results on. First the user profile is checked
    for a preference, then the session.
    :param request: Any self.request.
    :return: The proper city or None.
    """
    city_id = request.session.get("city_id", None)

    if hasattr(request.user, "profile") and hasattr(
            request.user.profile, "city"):
        return request.user.profile.city
    elif request.session.get("city_id", None):
        return City.objects.get(pk=city_id)
    else:
        return None


def query_sort(get, qs):
    """
    This is a helper function for use inside get_queryset.
    :param get: A self.request.GET object possibly containing a querystring
    parameter for sorting advertisements.
    :param qs: The queryset for a category or subcategory.
    :return: A sorted queryset.
    """

    if "price" in get and get["price"] == "low":
        qs = qs.order_by("price")
    elif "price" in get and get["price"] == "high":
        qs = qs.order_by("-price")
    elif "modified" in get and get["modified"] == "new":
        qs = qs.order_by("-modified_time")
    elif "modified" in get and get["modified"] == "old":
        qs = qs.order_by("modified_time")

    return qs


class MainPageView(ListView):
    template_name = "advertisements/main_page.html"
    context_object_name = "categories"

    def get_queryset(self):
        """
        :return: A queryset of all categories and thier associated
        subcategories.
        """
        logger.debug("On main page")
        qs = []
        for cat in Category.objects.select_related().all():
            qs.append((cat, SubCategory.objects.filter(category=cat)))

        return qs

    def get_context_data(self, **kwargs):
        """
        If the session has a city selected 'city_title' will be created with
        its title.
        'cities' is a list of all cities in the database which are placed
        in the template with redirect links to select or change the city
        for the current session.
        """
        context = super().get_context_data(**kwargs)
        city = get_current_city(self.request)

        if city:
            context["city_title"] = city.title

        context["cities"] = City.objects.all()
        return context


class CategoryView(ListView):

    template_name = "advertisements/subcategory.html"
    context_object_name = "advertisements"
    paginate_by = 20

    def get_queryset(self):
        """
        :return: A queryset filtered by city and category.
        """
        logger.debug("category test")

        category = Category.objects.get(pk=self.kwargs["pk"])
        city = get_current_city(self.request)
        logger.debug("category: {}".format(category))
        logger.debug("category city: {}".format(city))

        qs = Advertisement.objects.select_related("city").filter(
            subcategory__category=category)

        if city:
            qs = qs.filter(city__id=city.id)

        return query_sort(self.request.GET, qs)

    def get_context_data(self, **kwargs):
        """
        view is the display view ('list', 'thumb', or 'gallery') selected
        by the user.
        """
        logger.info("category info")
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(pk=self.kwargs["pk"])
        context["category"] = category

        view = self.request.GET.get("view", "list")
        context['view'] = view
        return context


class SubCategoryView(ListView):
    """
    This view is the same as CategoryView outside of the category filtering.
    """
    template_name = "advertisements/subcategory.html"
    context_object_name = "advertisements"
    paginate_by = 20

    def get_queryset(self):
        logger.debug("test")

        subcategory = SubCategory.objects.get(pk=self.kwargs["pk"])
        logger.debug("subcat: {}".format(subcategory))

        city = get_current_city(self.request)
        logger.debug("city: {}".format(city))

        qs = Advertisement.objects.select_related("city").filter(
            subcategory=subcategory)
        if city:
            qs = qs.filter(city__id=city.id)

        return query_sort(self.request.GET, qs)

    def get_context_data(self, **kwargs):
        logger.debug("subcategory context")
        context = super().get_context_data(**kwargs)
        category = SubCategory.objects.get(pk=self.kwargs["pk"])
        context["category"] = category

        view = self.request.GET.get("view", "list")
        context['view'] = view
        return context


class AdvertisementDetail(DetailView):
    model = Advertisement
    template_name = "advertisements/advertisement_detail.html"
    context_object_name = "advertisement"


class AdvertisementCreate(CreateView):
    model = Advertisement
    form_class = AdvertisementForm
    success_url = reverse_lazy("main_page")
    template_name = "advertisements/advertisement_create.html"

    def form_valid(self, form):
        if self.request.user.pk:
            form.instance.user = self.request.user
        form.instance.city = get_current_city(self.request)
        return super().form_valid(form)


class AdvertisementUpdate(LoginRequiredMixin, UpdateView):
    model = Advertisement
    form_class = AdvertisementUpdateForm
    template_name = "advertisements/advertisement_update.html"
    success_url = reverse_lazy("main_page")


class AdvertisementDelete(DeleteView):
    model = Advertisement
    template_name = "advertisements/advertisement_delete.html"
    success_url = reverse_lazy("main_page")


class AllCityList(ListView):
    model = City
    context_object_name = "cities"
    template_name = "advertisements/all_cities.html"


class CityRedirect(RedirectView):
    pattern_name = "city_redirect"
    permanent = False

    def get_redirect_url(self, *args, **kwargs):
        logger.debug("city redirect")
        chosen_city = get_object_or_404(City, pk=self.kwargs["id"])
        logger.debug("chosen_city: {}".format(chosen_city))

        self.request.session["city_id"] = chosen_city.id
        logger.debug("city_id: {}".format(chosen_city.id))

        if self.request.user.pk:
            logger.debug("user pk: {}".format(self.request.user.pk))
            self.request.user.profile.city = chosen_city
            self.request.user.profile.save()
        return reverse("main_page")


class UserDetail(LoginRequiredMixin, ListView):
    template_name = "advertisements/user_detail.html"
    context_object_name = "advertisements"

    def get_queryset(self):
        """
        :return: All of the users advertisements, sorted by the most recently
        created or modified.
        """

        profiled_user = User.objects.get(pk=self.kwargs['pk'])
        return Advertisement.objects.filter(
            user=profiled_user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        profiled_user = User.objects.get(pk=self.kwargs['pk'])
        context["profiled_user"] = profiled_user
        context["user_match"] = self.request.user == profiled_user

        user_token = Token.objects.filter(user=profiled_user)[0]
        context["token"] = user_token

        new_token = self.request.GET.get("token")
        if new_token == "new":
            user_token.delete()
            context["token"] = Token.objects.create(user=profiled_user)

        return context

advertisements/templates/advertisements/advertisement_create.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <h1>Create Advertisement</h1>
    <form method="post" action="{% url "ads:advertisement_create" %}" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons submit="Create" %}{% endbuttons %}
    </form>

{% endblock %}

advertisements/templates/advertisements/advertisement_delete.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block title %}Deletion{% endblock %}

{% block content %}
    <h1>Advertisements</h1>
<form action="{% url 'ads:advertisement_delete' advertisement.id %}" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>


{% endblock %}

advertisements/templates/advertisements/advertisement_detail.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block content%}
<h3>
{{ advertisement.title }}
${{ advertisement.price }}
{{ advertisement.city }}
</h3>
    {% if advertisement.image %}

    <img src="{{ advertisement.image.url }}" height="600" width="600">

    {% endif %}
    <br>
    <br>
    <h4>
{{ advertisement.description }}
</h4>
{% endblock %}

advertisements/templates/advertisements/advertisement_update.html
{% extends 'advertisements/base.html' %}

{% load bootstrap3 %}

{% block content %}
    <h1>Update Advertisement</h1>
    <form method="post" action="{% url 'ads:advertisement_update' advertisement.id %}" enctype='multipart/form-data'>
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" name="submit" value="update">
    </form>

{% endblock %}

advertisements/templates/advertisements/all_cities.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block content %}
<ul>
{% for city in cities %}
    <li><a href="{% url 'city_redirect' city.id %}"> {{ city.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}

advertisements/templates/advertisements/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Emporium{% endblock %}</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <script src="{% static "js/jquery-2.2.3.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <link href="{% static "font-awesome-4.6.3/css/font-awesome.min.css" %}" rel="stylesheet">
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <link rel="stylesheet" href="{% static 'css/advertisment_styles.css' %}">



</head>
<body>

<div class="container-fluid header_bar">



    {% if user.is_authenticated %}
        <div class="greeting col-md-3">Greetings <a href="{% url 'user_detail' user.id %}"> {{ user.username }}</a></div>
        <div class="greeting col-md-3"><a href="{% url 'logout' %}">Logout</a> </div>
        <div class="greeting col-md-3"><a href="{% url 'ads:advertisement_create' %}">Create a post</a> </div>
    {% else %}
        <div class="greeting col-md-3"><a href="{% url 'register' %}">Register</a> </div>
        <div class="greeting col-md-3"><a href="{% url 'login' %}">Login</a> </div>

        <div class="col-md-2">
            <a href='{% provider_login_url "facebook" %}'><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
        </div>

        <div class="col-md-2">
            <a href='{% provider_login_url "github" %}' ><i class="fa fa-github github_login" aria-hidden="true"></i></a>
        </div>
    {% endif %}
    <div class="greeting col-md-2"><a href="{% url 'main_page' %}">Main Page</a></div>
        </div>




<div class="background">
    <div class="container">



    {% block content %}
    {% endblock %}
    </div>

</div>

{% block js %}{% endblock %}

</body>
</html>

advertisements/templates/advertisements/category.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block content %}

    <span class="title_text"><h1>{{ category.title }}</h1></span>


    <div class="btn-group" role="group">
  <a href="?price=high"><button type="button" class="btn btn-default">high price</button></a>
  <a href="?price=low"><button type="button" class="btn btn-default">low price</button></a>
  <a href="?modified=new"><button type="button" class="btn btn-default">newest</button></a>
    <a href="?modified=old"><button type="button" class="btn btn-default">oldest</button></a>
    </div>
    <br>
    <br>

    <div class="btn-group" role="group">
        <a href="?view=list"><button type="button" class="btn btn-default">list</button></a>
        <a href="?view=thumb"><button type="button" class="btn btn-default">thumb</button></a>
        <a href="?view=gallery"><button type="button" class="btn btn-default">gallery</button></a>
    </div>
<br>
    <br>
<div class="list-group">
<br>
    {% for ad in advertisements %}


        {% if view == "thumb" or view == "gallery" %}
            <li  class="list-group-item ad_listing">
            <a href="{% url 'ads:advertisement_detail' ad.id %}">

            {% if ad.image and view == "thumb" %}
                <img src="{{ ad.image.url }}" height="100" width="100">
            {% elif ad.image and view == "gallery" %}
               <div> <img src="{{ ad.image.url }}" height="400" width="400"></div>
            {% endif %}

            <span class="dark_text">
            {{ ad.display_date }}

             {{ ad.title }}
            {% if ad.price %}
                ${{ ad.price }}
            {% endif %}
             {{ ad.city }}
                <br>
            </span>
            </a>
            </li>

        {% else %}
            <li  class="list-group-item ad_listing">
            <a href="{% url 'ads:advertisement_detail' ad.id %}">
            <span class="dark_text">
            {{ ad.display_date }}
             {{ ad.title }}
            {% if ad.price %}
                ${{ ad.price }}
            {% endif %}
             {{ ad.city }}
                <br>
            </span>
            </a>
            </li>

        {% endif %}



    {% endfor %}
<br>

</div>
    {% bootstrap_pagination page_obj %}
{% endblock %}

advertisements/templates/advertisements/main_page.html
{% extends "advertisements/base.html" %}
{% block content%}


<div class="container-fluid">
  <div class="row">

{#<div class="col-md-2"></div>#}

  <div class="col-md-9">

  {% if city_title %}
    <div class="text-center title">
      <h2>Aaron's Emporium</h2>
    <p><h2> {{ city_title }}</h2></p>
    </div>
    {% else %}
        <center><h2>Aaron's Emporium</h2></center>
    {% endif %}
  <br>

  <ul class="list-group">
{% for category in categories %}
    <li  class="col-lg-6">
    <div>
    <span class="list-group-item category_item category_text text-center">
        <a href="{% url 'category_list' category.0.id %}">
            <span class="dark_text">{{ category.0 }}</span>
        </a>
    </span>
    <ul class="list-group">
                {% for sub in category.1 %}
            <li  class="list-group-item subcategory_item">
            <a class="subcategory_text" href="{% url 'subcategory_list' sub.id %}">
                <span class="dark_text">{{ sub.title }}</span>
            </a>
            </li>
        {% endfor %}
    </ul>
    </div>
    </li>
{% endfor %}
  </ul>
  </div>

  <div class="col-md-3">

<h2>More Cities</h2>
<ul class="list-group">

<br>
{% for city in cities %}
<li  class="list-group-item city_item"><a href="{% url 'city_redirect' city.id %}"><span class="dark_text"> {{ city.title }}</span></a></li>
{% endfor %}
<br>

</ul>

</div>

</div>
</div>

{% endblock %}

// javascript block here.

advertisements/templates/advertisements/subcategory.html
{% extends "advertisements/category.html" %}


advertisements/templates/advertisements/user_detail.html
{% extends "advertisements/base.html" %}
{% load bootstrap3 %}

{% block title %}Bookmark List{% endblock %}

{% block content %}
<h1>{{ profiled_user.username }}</h1>

    {% if user_match %}
        <h5>User Auth Token: {{ token }}</h5>
        <a href="?token=new"><button type="button" class="btn btn-default">New Auth Token</button></a>
    {% endif %}
<ul>
{% for ad in advertisements %}
    <br>
    <li  class="list-group-item">
        {{ ad.display_date }}
        <a href="{% url 'ads:advertisement_detail' ad.id %}"> {{ ad.title }}</a>
        {% if ad.price %}
            ${{ ad.price }}
        {% endif %}
         {{ ad.city }}
            <br>
    </li>
    {% if user_match %}
        <li><a href="{% url 'ads:advertisement_update' ad.id %}"> update</a></li>
        <li><a href="{% url 'ads:advertisement_delete' ad.id %}">delete</a> </li>
    {% endif %}
{% endfor %}
</ul>


{% endblock %}